version: 0.1

phases:
  pre_build:
    commands:
      - echo "STARTING THE BUILD CONOR"
      - npm install
      - npm install -g parcel-bundler
      - npm test

  build:
    commands:
      - npm run build 
      - cp -a ./dist/. ./

artifacts:
  files:
    - ./*
