version: 0.1

phases:
  pre_build:
    commands:
      - echo "STARTING THE BUILD CONOR"
      - yarn
      - yarn add -g parcel-bundler
      - yarn test

  build:
    commands:
      - yarn build 

artifacts:
  files:
    - ./*
    - src/*
    - dist/*
